# Cloudflare Pages 配置文件
name = "sydf-cc"
compatibility_date = "2024-06-24"

[build]
command = "echo 'No build step required for static site'"
publish = "."

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"

# 页面规则
[[pages_build_output_dir]]
# 静态文件目录
dir = "."

# 自定义域名配置（如果需要）
# [custom_domains]
# domains = ["sydf.cc", "www.sydf.cc"]
