/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseResultLayout: typeof import('./../components/divination/results/BaseResultLayout.vue')['default']
    DivinationInput: typeof import('./../components/divination/DivinationInput.vue')['default']
    DivinationResult: typeof import('./../components/divination/DivinationResult.vue')['default']
    InspirationPanel: typeof import('./../components/divination/InspirationPanel.vue')['default']
    LiuyaoResult: typeof import('./../components/divination/results/LiuyaoResult.vue')['default']
    MarkdownRenderer: typeof import('./../components/common/MarkdownRenderer.vue')['default']
    MeihuaResult: typeof import('./../components/divination/results/MeihuaResult.vue')['default']
    QimenResult: typeof import('./../components/divination/results/QimenResult.vue')['default']
    ResultHeader: typeof import('./../components/divination/results/ResultHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/layout/Sidebar.vue')['default']
    SsgwResult: typeof import('./../components/divination/results/SsgwResult.vue')['default']
    StreamingMarkdown: typeof import('./../components/common/StreamingMarkdown.vue')['default']
    TarotResult: typeof import('./../components/divination/results/TarotResult.vue')['default']
    TarotSpreadSelector: typeof import('./../components/divination/TarotSpreadSelector.vue')['default']
    TopBar: typeof import('./../components/layout/TopBar.vue')['default']
    YaoSymbol: typeof import('./../components/divination/common/YaoSymbol.vue')['default']
  }
}
